config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  get '/settings', to: 'users#settings'
  patch '/settings', to: 'users#update'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token

    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}

    has_secure_password
    validates :password, presence: true, length: { minimum: 8 }, allow_blank: true
    
    # returns the hash digest of the given string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # returns a random token
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # remembers a user in the database for use in persistent sessions
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # returns true if the given token matches the digest
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # forgets a user
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def hello
    render text: "bonjour, monde!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        @user = User.find_by(email: params[:session][:email].downcase)
        if @user.nil?
            flash.now[:danger] = "Email not found."
            render 'new'
        elsif !@user.authenticate(params[:session][:password])
            flash.now[:danger] = "Wrong password."
            render 'new'
        else
            flash[:success]= "Nice!"
            log_in @user
            params[:session][:remember_me] == '1' ? remember(@user) : 
                forget(@user)
            redirect_back_or @user
        end
    end

    def destroy
        log_out if logged_in?
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
    before_action :correct_user, only: [:edit, :update]
    before_action :admin_user, only: [:destroy]

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def index
        @users = User.paginate(page: params[:page])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the Sample App"
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = "Profile updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = "User deleted"
        redirect_to users_url
    end

    private

        def user_params
            params.require(:user).permit(:name, :email, :password,
                                         :password_confirmation, :animal)
        end

        # before filters
        
        # confirms a logged-in user
        def logged_in_user
            unless logged_in?
                store_location
                flash[:danger] = "Please log in."
                redirect_to login_url
            end
        end

        # confirms the correct user
        def correct_user
            @user = User.find(params[:id])
            redirect_to(root_url) unless current_user?(@user)
        end

        # confirms user is admin
        def admin_user
            redirect_to(root_url) unless current_user.admin?
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # logs in the given user
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def logged_in?
        !current_user.nil?
    end
    
    # forgets a persistent session
    def forget(user)
        user.forget()
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    # logs out the current user
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    # redirects to stored location (or to the default)
    def redirect_back_or(default)
        redirect_to(session[:fowarding_url] || default)
        session.delete(:fowarding_url)
    end

    # stores the URL trying to be accessed
    def store_location
        session[:fowarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

    # Returns the Gravatar for the givenn user.
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "sample_app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav nav-pills navbar-right">
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "users", users_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "profile", current_user %></li>
                    <li><%= link_to "settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to "log out", logout_path, method: "delete" %>
                    </li>
                </ul>
            </li>
        <% else %>
            <li><%= link_to "log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
 <!--[if lt IE9]> 
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Something something web yay hey hoy!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Alien stuff.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  I can't help you. You must help yourself. Be confident!
  I'm missing her.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Sample App</h1>
  
  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/', id: "rails_logo" %>

<% if logged_in? %>
    <% if current_user.animal == "cat" %>
        <%= image_tag("kitten.png", alt: "Every webpage needs a kitten.", id: "kitten-big") %>
    <% elsif current_user.animal == "rat" %>
        <%= image_tag("rat.png", alt: "Rats are cute.", id: "rat") %>
    <% else %>
        <%= image_tag("dog.jpg", alt: "Good dog.", id: "dog") %>
    <% end %>
<% else %>
  <%= image_tag("kitten.png", alt: "Every webpage needs a kitten.", id: "kitten") %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:to_url)) do |f| %>
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, 
        class: 'form-control' %>

    <%= f.label :animal, class: 'dropdown'%>
    <%= f.select :animal, ["cat", "dog", "rat"] %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete,
            data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<% provide(:to_url, "/users/#{params[:id]}") %>
<h1>Update your profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:button_text, "Create my account") %>
<% provide(:to_url, signup_path) %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <asside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
            <br/>
            <p><b>Email: </b><%= @user.email %></p>
            <p><b>Created at: </b><%= @user.created_at %></p>
            <p><b>Updated at: </b><%= @user.updated_at %></p>
        </section>
    </aside>
</div>
<%= Time.now %>

app/views/users/update.html.erb
<% provide title: "Settings" %>
<div class="row">
    <div class="col-md-3 col-md-offset-0">
        <%= form_tag do %> 
            <%= radio_button_tag(:animal, "dog") %>
            <%= label_tag(:animal_dog, "dog") %>
            <%= radio_button_tag(:animal, "kitten") %>
            <%= label_tag(:animal_kitten, "kitten") %>
            <%= submit_tag("Submit") %>
        <% end %>
    </div>
</div>